version: "3.8"

services:
  storybook:
    image: ghcr.io/codelyr/design-system:latest
    ports:
      - target: 80
        published: 8085
        protocol: tcp
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "com.centurylinklabs.watchtower.enable=true"

networks:
  internal:
    driver: overlay
    internal: true
    name: design_system_internal
