import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBars,
  faBell,
  faBookmark,
  faCalendar,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleXmark,
  faClock,
  faCloud,
  faCopy,
  faDownload,
  faEllipsis,
  faEllipsisVertical,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFile,
  faFilter,
  faGear,
  faGlobe,
  faGrip,
  faHeart,
  faHouse,
  faImage,
  faLink,
  faLock,
  faMagnifyingGlass,
  faMoon,
  faPaperclip,
  faPen,
  faPhone,
  faPlus,
  faRightFromBracket,
  faRightToBracket,
  faRotate,
  faShare,
  faSliders,
  faSort,
  faStar,
  faSun,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faUser,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

import {
  faBell as faBellRegular,
  faBookmark as faBookmarkRegular,
  faCalendar as faCalendarRegular,
  faClock as faClockRegular,
  faCopy as faCopyRegular,
  faEnvelope as faEnvelopeRegular,
  faEye as faEyeRegular,
  faEyeSlash as faEyeSlashRegular,
  faFile as faFileRegular,
  faHeart as faHeartRegular,
  faImage as faImageRegular,
  faStar as faStarRegular,
  faUser as faUserRegular,
} from '@fortawesome/free-regular-svg-icons';

import {
  faGithub,
  faGoogle,
  faLinkedin,
  faSlack,
  faXTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';

export const DS_ICONS = {
  // Navigation
  'arrow-down': faArrowDown,
  'arrow-left': faArrowLeft,
  'arrow-right': faArrowRight,
  'arrow-up': faArrowUp,
  'chevron-down': faChevronDown,
  'chevron-left': faChevronLeft,
  'chevron-right': faChevronRight,
  'chevron-up': faChevronUp,
  house: faHouse,

  // Actions
  check: faCheck,
  copy: faCopy,
  'copy-outline': faCopyRegular,
  download: faDownload,
  filter: faFilter,
  link: faLink,
  'magnifying-glass': faMagnifyingGlass,
  pen: faPen,
  plus: faPlus,
  rotate: faRotate,
  share: faShare,
  sort: faSort,
  trash: faTrash,
  upload: faUpload,
  xmark: faXmark,

  // Status & Feedback
  'circle-check': faCircleCheck,
  'circle-exclamation': faCircleExclamation,
  'circle-info': faCircleInfo,
  'circle-xmark': faCircleXmark,
  'triangle-exclamation': faTriangleExclamation,

  // Objects
  bell: faBell,
  'bell-outline': faBellRegular,
  bookmark: faBookmark,
  'bookmark-outline': faBookmarkRegular,
  calendar: faCalendar,
  'calendar-outline': faCalendarRegular,
  clock: faClock,
  'clock-outline': faClockRegular,
  cloud: faCloud,
  envelope: faEnvelope,
  'envelope-outline': faEnvelopeRegular,
  eye: faEye,
  'eye-outline': faEyeRegular,
  'eye-slash': faEyeSlash,
  'eye-slash-outline': faEyeSlashRegular,
  file: faFile,
  'file-outline': faFileRegular,
  globe: faGlobe,
  heart: faHeart,
  'heart-outline': faHeartRegular,
  image: faImage,
  'image-outline': faImageRegular,
  paperclip: faPaperclip,
  phone: faPhone,
  star: faStar,
  'star-outline': faStarRegular,

  // UI
  bars: faBars,
  ellipsis: faEllipsis,
  'ellipsis-vertical': faEllipsisVertical,
  gear: faGear,
  grip: faGrip,
  lock: faLock,
  moon: faMoon,
  'right-from-bracket': faRightFromBracket,
  'right-to-bracket': faRightToBracket,
  sliders: faSliders,
  sun: faSun,
  user: faUser,
  'user-outline': faUserRegular,

  // Brands
  github: faGithub,
  google: faGoogle,
  linkedin: faLinkedin,
  slack: faSlack,
  'x-twitter': faXTwitter,
  youtube: faYoutube,
} as const;

export type DsIconName = keyof typeof DS_ICONS;
